name: Aula 14 - K6 Browser

on:
  workflow_dispatch:

jobs:
  k6-browser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar k6 com suporte a browser
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg \
            --keyserver hkp://keyserver.ubuntu.com:80 \
            --recv-keys C780D0BDB1A69C86
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" \
            | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6 -y

      - name: Rodar K6 Browser
        run: |
          K6_BROWSER_ENABLED=true k6 run --browser k6/aula-14-browser.js