name: Aula 3 - Matrix Jobs

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  matix-example:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ambiente: [dev, staging, prod]

    steps:
      - name: Mostrar ambiente
        run: | 
          echo Rodando no ambiente: ${{ matrix.ambiente }}

      - name: Simular trabalho
        run: sleep 3