name: Aula 4 - Recursos do Runner

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  recursos-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar CPU
        run: nproc

      - name: Mostrar memÃ³ria
        run: free -h

      - name: Mostrar disco
        run: df -h

      - name: Simular carga de CPU
        run: |
          echo "Consumindo CPU por 10 segundos..."  
          yes > /dev/null &
          yes > /dev/null &
          sleep 10
          killall yes