name: Aula 14 - K6 Browser

on:
  workflow_dispatch:

jobs:
  k6-browser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Rodar K6 Browser (xk6-browser)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/scripts \
            grafana/xk6-browser:latest \
            run /scripts/k6/aula-14-browser.js
