name: CI - Performance Tests

on:
  workflow_dispatch

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Executar testes de carga
        run: |
          echo "Rodando K6 / stress / chaos"
          sleep 5